name: {{name}}
description: {{description}}
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^8.0.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.5.1
  intl: ^0.18.0 #* Localization
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  #* Code generator
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
#  flutter_launcher_icons: ^0.13.1
#  flutter_native_splash: ^2.3.2
  #* Firebase
#  firebase_analytics: ^10.4.4
#  firebase_core: ^2.15.0
#  firebase_crashlytics: ^3.3.4
#  firebase_messaging: ^14.6.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  lint: ^2.3.0
  melos: ^5.3.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

#dependency_overrides:

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/




